[
  {
    "Name": "node_exporter",
    "Description": "",
    "MonitTemplate": {
      "SrcPathEnd": "monit",
      "DstPathEnd": "monit",
      "Path": "/tmp/tar-CmdExtractor671308218/monit"
    },
    "Templates": [
      {
        "SrcPathEnd": "bin/node_exporter_ctl",
        "DstPathEnd": "bin/node_exporter_ctl",
        "Path": "/tmp/tar-CmdExtractor671308218/templates/bin/node_exporter_ctl"
      },
      {
        "SrcPathEnd": "config/role.prom",
        "DstPathEnd": "config/role.prom",
        "Path": "/tmp/tar-CmdExtractor671308218/templates/config/role.prom"
      }
    ],
    "DeploymentJobTemplates": null,
    "Packages": [
      {
        "Name": "node_exporter"
      }
    ],
    "Properties": [
      {
        "Name": "node_exporter.log_format",
        "Description": "If set use a syslog logger or JSON logging",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.systemd_unit_whitelist",
        "Description": "Regexp of systemd units to whitelist. Units must both match whitelist and not match blacklist to be included",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.filesystem_ignored_fs_types",
        "Description": "Regexp of filesystem types to ignore for filesystem collector",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.sysfs",
        "Description": "sysfs mountpoint",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collectors.enabled",
        "Description": "Comma-separated list of collectors to use",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.log_level",
        "Description": "Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal]",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.diskstats_ignored_devices",
        "Description": "Regexp of devices to ignore for diskstats",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.systemd_private",
        "Description": "Establish a private, direct connection to systemd without dbus",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.procfs",
        "Description": "procfs mountpoint",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.netdev_ignored_devices",
        "Description": "Regexp of net devices to ignore for netdev collector",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.ntp_version",
        "Description": "NTP protocol version",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.ntp_server",
        "Description": "NTP server to use for ntp collector",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.systemd_unit_blacklist",
        "Description": "Regexp of systemd units to blacklist. Units must both match whitelist and not match blacklist to be included",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.web.port",
        "Description": "Port on which to expose metrics and web interface",
        "Default": "9100",
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.web.telemetry_path",
        "Description": "Path under which to expose metrics",
        "Default": null,
        "Example": null,
        "Examples": null
      },
      {
        "Name": "node_exporter.collector.filesystem_ignored_mount_points",
        "Description": "Regexp of mount points to ignore for filesystem collector",
        "Default": null,
        "Example": null,
        "Examples": null
      }
    ]
  }
]